### ISSUE TITLE
T-ARRI_REVEAL_Tone DCTL not working

### ISSUE THREAD

**Issue by balaji-dop** [priikone/aces-looks#1]
@priikone 
Hi. The T-ARRI_REVEAL_Tone DCTL is not working. The CLF and ACEScct LUT seems to work fine without any issue.

**Comment by priikone** [comment]
Thanks for reporting.  I just tested with Resolve 18 and T-ARRI_REVEAL_Tone DCTL works for me.  Do you have problems with other DCTLs also or just with this one?

**Comment by balaji-dop** [comment]
Thats wierd. I'm using Resolve 18.0.1 in Windows. Except REVEAL_Tone DCTL all other DCTLs works fine for me.

**Comment by priikone** [comment]
Start by deleting the old ACESLooks directory and copy it again into place and see if that helps.  Maybe something went wrong last time you copied it.  The DCTLs are almost identical to each other, the only difference is the path to the ACEScct LUT, so if the LUT file is in place it should work.

**Comment by balaji-dop** [comment]
Oh that worked!! Is the Reveal colorimetry coming up ? And thank u very much for the work you putting in !! This seems to be the best way for me to get the look in color managed pipeline matching exactly what i see on-set.

**Comment by priikone** [comment]
I can't promise there will be Reveal colorimetry coming up.  The new Arri transform is very different from ACES1.  It seems to be a hue-preserving transform while ACES1 very much isn't.  So even in the case where I were to match the colors ACES output transform would still skew those colors (rather than preserving the hue).  I might be able to compensate for that but it might cause other problems.  What it means in the end is that there would be narrower range of colors that actually match the original.  Colorful highlights would not match well, for example fire and pyro effects in general would not match at all (red would skew to orange, orange would skew to yellow, etc.).  Maybe it's not that critical though for these LMTs.  I'm not sure.  What do you think?  Would that be a problem for your workflow?

**Comment by balaji-dop** [comment]
Yeah i guess i understand what you mean. I checked comparing the new C4 LUTS from ARRI and ACES1.3 . The results in the Reds are very different and ACES treats them sorta out of gamut, while rec709 transform from ARRI seems to treat the Reds as denser colors rather than saturated or warm. Have you tried experimenting with the new ACES2.0 Rec709 transforms (three versions of it)? They seem to be an improvement over ACES1.3 Rec709 ? Since projects for Netflix and few other OTTs demand ACES workflow, i guess using an LMT thats close to C4 luts would be a necessity in the future, because me and most of the DPs would be using Arri Lut for on-set monitoring and lighting too . For my last work i almost gave up color managed workflow , because i got very much used to the ARRI C3 color science for that particular project, but then just at the right time i found T-ARRI Tone and colorimetry which saved me from lot of steps to achieve the basic look which i saw on set to start off my grade in ACES.

**Comment by priikone** [comment]
It's good to hear you've found the LMTs helpful.  And you're spot on about the reds with Reveal vs the old one.  It being a hue-preserving it will keep reds red and oranges orange, and trying to reproduce that through ACES1 is difficult, and at some point the skew will always happen anyway.  I haven't tried yet to compensate for that so I'm not sure how effective that would be, though.

Yeah I've used ACES2 candidates extensively but I haven't wanted to spend the time to do these LMTs through them until we have better understanding of the direction ACES2 will take.  Two of the candidates are hue-preserving so doing something like the Reveal through them would be easier.  By the way, if you haven't filled the ACES2 output transform survey yet (https://community.acescentral.com/t/aces-output-transform-evaluation-and-feedback-3-candidates/4498) please do so, if you've tried the candidate transforms.  The project needs more feedback on the candidates.  Even incomplete feedback is better than no feedback.  Not all questions have to be answered.

**Comment by balaji-dop** [comment]
Sure would do !! And thanks again .. Cheers !
