### ISSUE TITLE
DCTL error

### ISSUE THREAD

**Issue by sharktacos** [priikone/aces-looks#2]
Getting the error "Error Processing DaVinci CTL
Resolve 18.0.1 build 3

**Comment by priikone** [comment]
I've been using them without issues with Resolve 18.  If you had it installed already before, then start by deleting the old ACESLooks directory and then copy the new ACESlooks directory again, and see if that helps.  If that doesn't help then please take the diagnostics (from Help menu) and check what the actual error is you're getting.

**Comment by sharktacos** [comment]
Ah my mistake was that I had copied the individual DCTL files, rather than the ACESlooks folder, as I had not realized the DCTLs use the cube LUTs. All working now thanks!

May I ask: is there any advantage to using the DCTLs instead of the CLFs?

**Comment by priikone** [comment]
Good that you got it working.  At least some of the older versions of Resolve 17 had performance problems with CLFs, though it might be GPU related as well.  DCTL can be a workaround in those cases.  They should produce identical output.

**Comment by sharktacos** [comment]
Makes sense. 
BTW, This is a super amazing resource! So glad you made it!

**Comment by priikone** [comment]
Hope you find it useful!
