### ISSUE TITLE
Using .CLF LMT in Baselight Look Operator

### ISSUE THREAD

**Issue by balaji-dop** [priikone/aces-looks#3]
Hi. Hope you're doing well. I have been using your LMTs for a long time in Resolve and Nuke without any issues. Now for a project I had to work in Baselight and I would like to use the LMTs in it. I'm able to use .cube file through Look Operator using .fllook support file and also as a LUT operator with Inspace and Outspace as ACEScct. But I'm not able to use the CLF by using the same method with ACES2065 as colorspace. 

So can you let me know how to make use of CLF files in Baselight, since you have mentioned CLFs are technically better?

Thank you.

**Comment by priikone** [comment]
I'm not sure if Baselight yet supports CLFs.  I know they're working on ACES AMF and certainly with that will come support for CLFs as well, but I don't have a license for Baselight right now so I cannot test if CLFs work with the latest version.  It's probably best to ask that question directly from Filmlight.

At this moment there shouldn't be any quality difference with any of the ACESLooks LMTs as cube LUTs or as CLFs, or as DCLTs.  CLFs (and DCTLs) apply the same LUTs internally with tetrahedral interpolation so they all should be pretty much identical. 

Hope that helps.

**Comment by balaji-dop** [comment]
Thank you! I’ve sent them an email regarding this, and in the meantime, I’d like to create a few basic LMTs, like having a less saturated image as a grading starting point. For example, tagging a LogC3-decoded image with ADX as the IDT—my colorist prefers an image that looks more like it came out of a film scanner. 

I noticed the LMT tools in your repo—are those the only tools you use for creating LMTs? Could you share any insights into the tools you use or provide a sample .nk file for creating LMTs while preserving linearity? I have read about the LMT creation in ACES forum, but still feel it's slightly less hands-on for my current level of understanding.

**Comment by priikone** [comment]
Yes, the tools that are in the repo are mostly the ones that I use in the creation of these LMTs. But the process of going about creating these LMTs can be quite convoluted.  I don't have a suitable .nk that I'm able share right now.  I have new versions of some of the tools coming up as I'm working on new LMTs for ACES v2.

In Nuke it's easy to create ACEScct LUTs.  It's just a CMSTestPattern and GenerateLUT nodes, with a grade in-between.  The resulting LUT would be applied in ACEScct and it would output ACEScct values.  Operations can be done in linear too, in which case the log-to-lin/lin-to-log transforms would also be done.  [ACEScctLUT.nk.txt](https://github.com/user-attachments/files/17821612/ACEScctLUT.nk.txt).  All ACESLooks LMTs are ACEScct internally, they just go from AP0<->AP1 ACEScct in the CLF or DCTL.  OCIO's [ociomakeclf](https://opencolorio.readthedocs.io/en/latest/guides/using_ocio/using_ocio.html#ociomakeclf) can be used to create such CLF from a LUT.

**Comment by balaji-dop** [comment]
Oh that's great! Thanks for sharing them!! 
Just having couple of questions regarding ACESv2:

1) Is the ACES1_Tone LMT for ACESv2 intended only to be used with its SDR ODTs? Because when i checked them through ST2084 ODT, it seems to be off.

2) And when I checked the difference between ACES1.3 and 2.0's HDR ODTs the output mid-gray option is not available anymore in 2.0. Do you know what made them to deprecate it or will it be made available when it's officially released? On the other hand ARRI also has stopped providing DW200 DRTs in their LogC4 package, even though in BT.2408 its mentioned 203 nits as diffused white. I tried to go through the forum on this but couldn't find any info. Would be great to know if you can share something on it.

**Comment by priikone** [comment]
> Is the ACES1_Tone LMT for ACESv2 intended only to be used with its SDR ODTs? Because when i checked them through ST2084 ODT, it seems to be off.

Do you mean when you compare it to ACES1 HDR ODT?  That would be off because in ACES1 the SDR and HDR has different contrast curves by design.  The LMT is matching it to the ACES1 SDR contrast.  However, you should be seeing fairly consistent behavior when using that LMT with ACES2 SDR and HDR Output Transforms.  The middle gray of course changes when going from SDR to HDR.

> And when I checked the difference between ACES1.3 and 2.0's HDR ODTs the output mid-gray option is not available anymore in 2.0. Do you know what made them to deprecate it or will it be made available when it's officially released?

I'm a member of the ACES2 working group and one of the developers of the ACES2 output transforms so I can provide some insight.  In ACES2 the tonescale algorithm automatically changes the middle gray based on the transform's peak luminance.  So, 100 nits transform has 10 nits middle gray, and 1000 nits is around ~14 nits.  This then means that if you'd want to create a new 540 nit transform it will automatically come up with a suitable middle gray for it.  Same if you'd want a 5000 nit transform.  So there's no more fixed middle gray values like there were in ACES1.  The transform naming has changed also and no longer includes the middle gray.  We worked very hard on the appearance match between SDR and HDR in ACES2 and it should be much much better compared to ACES1 (which wasn't good at all), and based on the feedback people so far seem quite happy with it.

Draft documentation for ACES2 transforms are available (subject to changes still) and the middle gray values can be seen here: https://draftdocs.acescentral.com/output-transforms/technical-details/tone-mapping/

**Comment by priikone** [comment]
BTW, I'm always interested in hearing where and how these LMTs are being used, so if you're able to share information about the shows or projects where you've used the LMTs that would be very welcome.

**Comment by balaji-dop** [comment]
> Do you mean when you compare it to ACES1 HDR ODT? That would be off because in ACES1 the SDR and HDR has different contrast curves by design. The LMT is matching it to the ACES1 SDR contrast. However, you should be seeing fairly consistent behavior when using that LMT with ACES2 SDR and HDR Output Transforms. The middle gray of course changes when going from SDR to HDR.

Ah no no, actually i meant the LMT does match perfectly the SDRs of v1.3 and v2, but Not the HDRs of v1.3 and v2.

  Let me share few images, with and without the LMT in a timeline that’s set to ACES2 DRT and comparing it against an ACES1.3 DRT timeline. I have 6 main images here to compare SDR (1 & 2) separately and HDR/PQ (3 & 4) separately. So in,

Scenario #1 (SDR only)
1. ACES1.3 Rec.709 ODT -compared to-
2. ACES1_Tone LMT + ACES2 v60 Rec.709 ODT
**1 & 2 perfectly matches**

<img width="1512" alt="1" src="https://github.com/user-attachments/assets/94b5abd7-918f-4ed2-a0c3-7a52b5ae0e3b">
<img width="1512" alt="2" src="https://github.com/user-attachments/assets/81c5a950-a96e-45a5-ae63-8e6876a37ef0">

Scenario #2 (HDR/PQ only)

3. ACES1.3 PQ 1000nits ODT -compared to-
4. ACES1_Tone LMT + ACES2 v60 PQ 1000nits ODT
**Contrast is boosted in 4, 3 & 4 doesn’t match** 

<img width="1512" alt="3" src="https://github.com/user-attachments/assets/c4d44d3d-e346-4e6b-8b35-8173f14c3f7c">
<img width="1512" alt="4" src="https://github.com/user-attachments/assets/16698187-5d4d-4576-89de-24a23209bf82">

And lastly without any LMT in,

Scenario #3 (HDR/PQ only)

5. ACES1.3 PQ 1000nits ODT -compared to-
6. ACES2 v60 PQ 1000nits ODT   

<img width="1512" alt="5" src="https://github.com/user-attachments/assets/fce82367-d958-4627-93a6-20acc0264643">
<img width="1512" alt="6" src="https://github.com/user-attachments/assets/47030e5d-d568-4410-a317-1d2bbe2e192b">



Scenario #3 again (HDR/PQ only)
7 & 8 with LAD image, 

<img width="1512" alt="7" src="https://github.com/user-attachments/assets/43249e41-da49-4e1c-b841-9411e9f14c70">
<img width="1512" alt="8" src="https://github.com/user-attachments/assets/f4fe6e9b-c5e1-4b02-a37c-4cd0de487a1e">


<img width="1512" alt="9-ramp" src="https://github.com/user-attachments/assets/e86bdda9-bc28-4443-9f83-7b5dfdc38251">
<img width="1512" alt="10-ramp" src="https://github.com/user-attachments/assets/a2d399af-eb5b-4a97-a984-d20687863caf">


9 & 10 with grey ramp to show the Tone difference between v1.3 and v2.   And I guess you must have known this difference already, but I would like to share my observation on this.

The Toe slightly lifts up and shoulder slightly goes down making the skin-tones look better in v1.3.   Though the difference is very mild on a backlight display, but seeing on a 150” Laser projection screen (after 48nits DolbyVision trim pass), it does make a clearly visible difference, especially in night-dark scenes. I was pushing to use ACESv2 ODT mainly because of its colorimetry which i really liked. We spent some hours in the Lab on deciding to which one to opt for the current project that we are working on, after some test we couldn’t help but prefer the v1.3 only for its tone-curve. 
Also since i’m from India and the lighting contrast ratio on any day is high, so having that extra bump in the Toe makes the contrast less harsher along with defined blacks, which couldn’t be compensated using grading tools on a shot-by-shot basis. Furthermore there's no dedicated roles as color scientists in our Labs to help us on this, so it's more of a personal task.

So my question is, since ACES1_Tone LMT only work for SDR scenario, for the HDR/PQ curve if i need another LMT, for eg. ACES1_PQ_Tone, does the provided tools in the repo must be enough to make it?

P.S:
HDR/PQ ODT Images (3 to 8) are Tonemapped to 100nits using DolbyVision.

**Comment by priikone** [comment]
>Ah no no, actually i meant the LMT does match perfectly the SDRs of v1.3 and v2, but Not the HDRs of v1.3 and v2.

Yeah, exactly, it doesn't. The reason is, as said, that in ACES1 SDR and HDR contrast doesn't match by design.  So one LMT isn't enough.  The problem isn't going to be only with the Tone Curve LMTs, the ACES1 colorimetric LMT (which I haven't published yet) won't match the ACES1 HDR either, for the same reason.  ACES1 is a problem in this case.  To some extent the same problem will be with ARRI Classic LMTs also, but not as bad...

So far I've decided to ignore this issue because ACES1 SDR and HDR appearance match is not great to begin with for that reason.

So, if I understood you correctly, you'd want to use ACES1 SDR contrast in ACES2 SDR, but use ACES1 HDR contrast in ACES2 HDR?  The problem with that will be that, yes it'll match the ACES1 versions nicely, but you won't have the best appearance match between ACES2 SDR and HDR with those two different LMTs.  Using two different LMTs will mean that you'll have different contrast in SDR and HDR.  I agree that the ACES1 Tone Curve LMT is "too much" for HDR.  But technically it looks "correct" in HDR given how contrasty the look is.

But yes, PQ version of the Tone Curve LMT could be created and there's [RipToneCurve.nk](https://github.com/priikone/aces-looks/blob/master/util/LMT_Tools/Nuke/RipToneCurve.nk).  That's the one I use to create the Tone Curve LMTs.  There's also example how to do it: [RipToneCurve_example.nk](https://github.com/priikone/aces-looks/blob/master/util/LMT_Tools/Nuke/RipToneCurve_example.nk).  In the PQ case, you'd use ACES1 1000 nit output transform, and ACES2 1000 nit *inverse* transform, and then sample the curve using the RipToneCurve.

But since you have a real life use case for this, I will see about adding "ACES1 SSTS Tone Curve LMT" later this week.  In ACES1 the SSTS curve is used in HDR and the SDR has its own, different, curve.

![05bec4a12139f2e7d46cb0bfac8e29ad72fe9026](https://github.com/user-attachments/assets/38fa1ef8-c37b-4257-b1f8-3db240c9db6c)

**Comment by priikone** [comment]
Ok, it's pushed now. It's named "T-ACES1_SSTS_Tone" and matches the ACES1 HDR SSTS 1000 nits contrast curve.  I did only cursory testing but it seems to match.

If you now compare that curve against ACES1 SDR you'll see that it won't match either...

**Comment by balaji-dop** [comment]
> So far I've decided to ignore this issue because ACES1 SDR and HDR appearance match is not great to begin with for that reason.
 
Oh yeah, I totally get it!

> So, if I understood you correctly, you'd want to use ACES1 SDR contrast in ACES2 SDR, but use ACES1 HDR contrast in ACES2 HDR?

Yes.

> The problem with that will be that, yes it'll match the ACES1 versions nicely, but you won't have the best appearance match between ACES2 SDR and HDR with those two different LMTs. Using two different LMTs will mean that you'll have different contrast in SDR and HDR. I agree that the ACES1 Tone Curve LMT is "too much" for HDR.

Exactly, but I'm only going to only one Tone Curve LMT, and it's for the PQ, since the SDR master is tonemapped through Dolby Vision, so the contrast basically comes from there. I guess the problem might be for the preview purpose with VFX/CG team where they might use SDR. Other than that all grade preview & final goes through DV.

> But yes, PQ version of the Tone Curve LMT could be created and there's RipToneCurve.nk. That's the one I use to create the Tone Curve LMTs. There's also example how to do it: RipToneCurve_example.nk. In the PQ case, you'd use ACES1 1000 nit output transform, and ACES2 1000 nit inverse transform, and then sample the curve using the RipToneCurve.

Oh wow, that's a great tip. Just was taking a look at the files  and figuring how to do for ACES1 and 2, and got your reply.


> Ok, it's pushed now. It's named "T-ACES1_SSTS_Tone" and matches the ACES1 HDR SSTS 1000 nits contrast curve. I did only cursory testing but it seems to match. If you now compare that curve against ACES1 SDR you'll see that it won't match either...

Much appreciated !! I'm cross referencing with the new one and the nk file on how to make such LMT in future if any other need arises ! Thank you so much for this and the kind replies!

**Comment by balaji-dop** [comment]
> In ACES2 the tonescale algorithm automatically changes the middle gray based on the transform's peak luminance. So, 100 nits transform has 10 nits middle gray, and 1000 nits is around ~14 nits. This then means that if you'd want to create a new 540 nit transform it will automatically come up with a suitable middle gray for it. Same if you'd want a 5000 nit transform. So there's no more fixed middle gray values like there were in ACES1. 


Ah okay! Let me know if I'm wrong. So technically it's not correct to preview and expose mid-gray with DW200 LUTs (which kindof matches SDR mid-gray value) while onset monitoring in HDR, [unlike that's mentioned here](https://cml.news/g/cml-general/message/2757) since the mid-gray is now a fixed one in ACES2?

<img width="1509" alt="12" src="https://github.com/user-attachments/assets/3c896725-29ad-43ca-8c11-08035927a2d4">


And only when working in post-production (through DolbyVision), we must use L3 mid offset to compensate for this lower mid-gray value for the SDR trim-pass? 

I got this doubt because when I looked at the Image 1 and 3, both 100nits SDR,

<img width="1512" alt="1" src="https://github.com/user-attachments/assets/94b5abd7-918f-4ed2-a0c3-7a52b5ae0e3b">
<img width="1512" alt="3" src="https://github.com/user-attachments/assets/c4d44d3d-e346-4e6b-8b35-8173f14c3f7c">

after tone mapping without L3 mid-offset, the exposure is 1-stop lower. 

So,
SDR ODT -> SDR display looks correct,
HDR ODT -> HDR display looks correct, 
but HDR ODT -> Tonemap -> SDR display gets darker, even though it was exposed 'correctly'.


Can you clarify me on this?


> We worked very hard on the appearance match between SDR and HDR in ACES2 and it should be much much better compared to ACES1 (which wasn't good at all), and based on the feedback people so far seem quite happy with it.

Yeah , I also like the ACES2 very much especially how it renders the highly saturated colors in both SDR & HDR. Incredible work !!! Kudos to you and the team !!

**Comment by balaji-dop** [comment]
> BTW, I'm always interested in hearing where and how these LMTs are being used, so if you're able to share information about the shows or projects where you've used the LMTs that would be very welcome.

Ofcourse! I have used C-ARRI, T-ARRI and T-ARRI_Reveal in several projects.

[https://balajisubramanyam.com/works/kaysay](https://balajisubramanyam.com/works/kaysay)
[https://balajisubramanyam.com/works/missing-me](https://balajisubramanyam.com/works/missing-me)
[https://balajisubramanyam.com/works/chithha](https://balajisubramanyam.com/works/chithha)
[https://balajisubramanyam.com/works/ayepulla](https://balajisubramanyam.com/works/ayepulla)

and some new ones which i don't have links to. Before i used to majorly shoot in ARRI and use ARRI LUTs non-color managed for its color science, but after knowing the LMTs always went with ACES.

**Comment by priikone** [comment]
> So technically it's not correct to preview and expose mid-gray with DW200 LUTs (which kindof matches SDR mid-gray value) while onset monitoring in HDR, [unlike that's mentioned here](https://cml.news/g/cml-general/message/2757) since the mid-gray is now a fixed one in ACES2?

I think every time when judging exposure from monitor with a view LUT that has exposure adjustment or lift of some kind will have consequences down stream when the view transform changes (like going to ACES).  And that may mean having to do exposure adjustment later.  I recommend testing and see what works best for your use case.

**Comment by balaji-dop** [comment]
> I think every time when judging exposure from monitor with a view LUT that has exposure adjustment or lift of some kind will have consequences down stream when the view transform changes (like going to ACES). And that may mean having to do exposure adjustment later. I recommend testing and see what works best for your use case.

That makes sense!

**Comment by priikone** [comment]
>Ofcourse! I have used C-ARRI, T-ARRI and T-ARRI_Reveal in several projects.

Thanks.  Looks great, good job!
